/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as publicIndexImport } from './routes/(public)/index'
import { Route as authLoginImport } from './routes/(auth)/login'
import { Route as protectedDashboardRouteImport } from './routes/(protected)/dashboard/route'
import { Route as protectedAdminRouteImport } from './routes/(protected)/admin/route'
import { Route as protectedDashboardIndexImport } from './routes/(protected)/dashboard/index'
import { Route as protectedAdminIndexImport } from './routes/(protected)/admin/index'

// Create/Update Routes

const publicIndexRoute = publicIndexImport.update({
  id: '/(public)/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const authLoginRoute = authLoginImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const protectedDashboardRouteRoute = protectedDashboardRouteImport.update({
  id: '/(protected)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const protectedAdminRouteRoute = protectedAdminRouteImport.update({
  id: '/(protected)/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const protectedDashboardIndexRoute = protectedDashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => protectedDashboardRouteRoute,
} as any)

const protectedAdminIndexRoute = protectedAdminIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => protectedAdminRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(protected)/admin': {
      id: '/(protected)/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof protectedAdminRouteImport
      parentRoute: typeof rootRoute
    }
    '/(protected)/dashboard': {
      id: '/(protected)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof protectedDashboardRouteImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginImport
      parentRoute: typeof rootRoute
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexImport
      parentRoute: typeof rootRoute
    }
    '/(protected)/admin/': {
      id: '/(protected)/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof protectedAdminIndexImport
      parentRoute: typeof protectedAdminRouteImport
    }
    '/(protected)/dashboard/': {
      id: '/(protected)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof protectedDashboardIndexImport
      parentRoute: typeof protectedDashboardRouteImport
    }
  }
}

// Create and export the route tree

interface protectedAdminRouteRouteChildren {
  protectedAdminIndexRoute: typeof protectedAdminIndexRoute
}

const protectedAdminRouteRouteChildren: protectedAdminRouteRouteChildren = {
  protectedAdminIndexRoute: protectedAdminIndexRoute,
}

const protectedAdminRouteRouteWithChildren =
  protectedAdminRouteRoute._addFileChildren(protectedAdminRouteRouteChildren)

interface protectedDashboardRouteRouteChildren {
  protectedDashboardIndexRoute: typeof protectedDashboardIndexRoute
}

const protectedDashboardRouteRouteChildren: protectedDashboardRouteRouteChildren =
  {
    protectedDashboardIndexRoute: protectedDashboardIndexRoute,
  }

const protectedDashboardRouteRouteWithChildren =
  protectedDashboardRouteRoute._addFileChildren(
    protectedDashboardRouteRouteChildren,
  )

export interface FileRoutesByFullPath {
  '/admin': typeof protectedAdminRouteRouteWithChildren
  '/dashboard': typeof protectedDashboardRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/': typeof publicIndexRoute
  '/admin/': typeof protectedAdminIndexRoute
  '/dashboard/': typeof protectedDashboardIndexRoute
}

export interface FileRoutesByTo {
  '/login': typeof authLoginRoute
  '/': typeof publicIndexRoute
  '/admin': typeof protectedAdminIndexRoute
  '/dashboard': typeof protectedDashboardIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(protected)/admin': typeof protectedAdminRouteRouteWithChildren
  '/(protected)/dashboard': typeof protectedDashboardRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(public)/': typeof publicIndexRoute
  '/(protected)/admin/': typeof protectedAdminIndexRoute
  '/(protected)/dashboard/': typeof protectedDashboardIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/'
    | '/admin/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/' | '/admin' | '/dashboard'
  id:
    | '__root__'
    | '/(protected)/admin'
    | '/(protected)/dashboard'
    | '/(auth)/login'
    | '/(public)/'
    | '/(protected)/admin/'
    | '/(protected)/dashboard/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  protectedAdminRouteRoute: typeof protectedAdminRouteRouteWithChildren
  protectedDashboardRouteRoute: typeof protectedDashboardRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  publicIndexRoute: typeof publicIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  protectedAdminRouteRoute: protectedAdminRouteRouteWithChildren,
  protectedDashboardRouteRoute: protectedDashboardRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
  publicIndexRoute: publicIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(protected)/admin",
        "/(protected)/dashboard",
        "/(auth)/login",
        "/(public)/"
      ]
    },
    "/(protected)/admin": {
      "filePath": "(protected)/admin/route.tsx",
      "children": [
        "/(protected)/admin/"
      ]
    },
    "/(protected)/dashboard": {
      "filePath": "(protected)/dashboard/route.tsx",
      "children": [
        "/(protected)/dashboard/"
      ]
    },
    "/(auth)/login": {
      "filePath": "(auth)/login.tsx"
    },
    "/(public)/": {
      "filePath": "(public)/index.tsx"
    },
    "/(protected)/admin/": {
      "filePath": "(protected)/admin/index.tsx",
      "parent": "/(protected)/admin"
    },
    "/(protected)/dashboard/": {
      "filePath": "(protected)/dashboard/index.tsx",
      "parent": "/(protected)/dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
